require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("./config/db");
const User = require("./models/User");
const Category = require("./models/Category");
const Product = require("./models/Product");
const Blog = require("./models/Blog");

const TN_NAMES = [
  "Karthikeyan Subramaniam", "Arun Prakash", "Dinesh Kumar Raja",
  "Vignesh Murugan", "Saravanan Velusamy",
];

async function seed() {
  await connectDB();

  await Promise.all([
    User.deleteMany({}),
    Category.deleteMany({}),
    Product.deleteMany({}),
    Blog.deleteMany({}),
  ]);

  await User.create({
    name: "Pragadheesh", email: "pragadheesh32@gmail.com", phone: "9087542052",
    address: "Zira HQ, Chennai, Tamil Nadu", username: "admin",
    password: "admin123", role: "admin",
  });

  // User.create (not insertMany) so the pre-save hashing hook actually runs
  await User.create(
    TN_NAMES.map((name, i) => ({
      name,
      email: name.toLowerCase().replace(/\s+/g, ".") + "@mail.com",
      phone: "98" + (40000000 + i * 1111).toString().slice(0, 8),
      address: `${12 + i}, Anna Nagar, Chennai, Tamil Nadu`,
      username: name.split(" ")[0].toLowerCase() + i,
      password: "customer123",
      role: "customer",
    }))
  );

  const categories = await Category.insertMany([
    { name: "Face Care", desc: "Cleansers, serums, moisturizers & sunscreen" },
    { name: "Beard Care", desc: "Beard oils, balms, shavers & grooming tools" },
    { name: "Hair Care", desc: "Shampoos, oils, clays & styling products" },
    { name: "Body Care", desc: "Body wash, soaps, lotions & deodorants" },
    { name: "Fragrances", desc: "Perfumes, colognes & eau de toilette" },
    { name: "Accessories", desc: "Grooming kits & tools" },
  ]);
  const byName = (n) => categories.find((c) => c.name === n)._id;

// Local product images (seeded into Product.imageUrl)
// Copied from zira-frontend/src/components/ZIRA_Product_Images into:
// zira-frontend/public/Zira_Products_Images
const localImage = (filename) => `/Zira_Products_Images/${filename}`;

  await Product.insertMany([
    // Beard Care
    { 
      name: "Oudh Reserve Beard Oil", 
      categoryId: byName("Beard Care"), 
      price: 1499, 
      stock: 34, 
      desc: "Aged oudh & argan, slow-cold pressed. Nourishes and conditions.",
      brand: "Zira Premium",
      rating: 4.8,
      reviews: 342,
      icon: "🪔",
      imageUrl: localImage("12_ZIRA_Beard_Oil.png"),
      ingredients: ["Oudh Oil", "Argan Oil", "Jojoba Oil"],

      benefits: ["Deep conditioning", "Shine enhancement", "Anti-itch"],
      bestFor: ["Long beards", "Thick beards", "Daily use"],
      skinType: ["All"],
      size: "50ml",
      discount: 10
    },
    {
      name: "Sandalwood Shave Balm",
      categoryId: byName("Beard Care"),
      price: 1199,
      stock: 21,
      desc: "Post-shave calm with Mysore sandal. Soothes irritation instantly.",
      brand: "Zira Premium",
      rating: 4.6,
      reviews: 215,
      icon: "🕯️",
      imageUrl: localImage("13_ZIRA_Beard_Balm.png"),
      ingredients: ["Sandalwood Oil", "Aloe Vera", "Glycerin"],

      benefits: ["Soothes irritation", "Prevents ingrown hairs", "Moisturizes"],
      bestFor: ["Sensitive skin", "Post-shave care", "Daily use"],
      skinType: ["Sensitive", "Normal"],
      size: "100ml",
      discount: 15
    },
    {
      name: "Beard Styling Wax",
      categoryId: byName("Beard Care"),
      price: 899,
      stock: 45,
      desc: "Strong hold wax for perfect beard shaping. Water-resistant formula.",
      brand: "Zira",
      rating: 4.5,
      reviews: 178,
      icon: "🧴",
      imageUrl: localImage("14_ZIRA_Beard_Wax.png"),
      ingredients: ["Beeswax", "Coconut Oil", "Cedarwood"],

      benefits: ["Strong hold", "Water-resistant", "Pleasant scent"],
      bestFor: ["Styling", "Long beards", "Events"],
      skinType: ["All"],
      size: "75ml",
      discount: 5
    },

    // Face Care
    {
      name: "Charcoal Detox Face Wash",
      categoryId: byName("Face Care"),
      price: 799,
      stock: 58,
      desc: "Activated charcoal, daily use. Deep cleanses and removes impurities.",
      brand: "Zira",
      rating: 4.7,
      reviews: 512,
      icon: "◆",
      imageUrl: localImage("01_ZIRA_Daily_Face_Wash.png"),
      ingredients: ["Activated Charcoal", "Tea Tree Oil", "Neem"],

      benefits: ["Deep cleansing", "Removes toxins", "Oil control"],
      bestFor: ["Oily skin", "Acne-prone", "Daily use"],
      skinType: ["Oily", "Combination"],
      size: "150ml",
      discount: 20
    },
    {
      name: "Moisturizing Face Cream",
      categoryId: byName("Face Care"),
      price: 1299,
      stock: 38,
      desc: "Lightweight hydration for men. Non-greasy, fast-absorbing formula.",
      brand: "Zira Premium",
      rating: 4.6,
      reviews: 289,
      icon: "🌿",
      imageUrl: localImage("07_ZIRA_Face_Moisturizer.png"),
      ingredients: ["Hyaluronic Acid", "Aloe Vera", "Green Tea"],

      benefits: ["Deep hydration", "Anti-aging", "Skin brightening"],
      bestFor: ["Dry skin", "Sensitive", "Daily care"],
      skinType: ["Dry", "Sensitive", "Normal"],
      size: "100ml",
      discount: 12
    },
    {
      name: "Face Scrub - Exfoliating",
      categoryId: byName("Face Care"),
      price: 649,
      stock: 52,
      desc: "Gentle exfoliating scrub for men. Remove dead skin cells weekly.",
      brand: "Zira",
      rating: 4.4,
      reviews: 198,
      icon: "✨",
      imageUrl: localImage("06_ZIRA_Face_Scrub.png"),
      ingredients: ["Walnut Shell Powder", "Tea Tree", "Mint"],

      benefits: ["Exfoliation", "Smooth texture", "Brightening"],
      bestFor: ["Weekly use", "All skin types", "Dull skin"],
      skinType: ["All"],
      size: "120ml",
      discount: 0
    },

    // Hair Care
    {
      name: "Matte Clay Pomade",
      categoryId: byName("Hair Care"),
      price: 999,
      stock: 65,
      desc: "Strong hold, zero shine. Perfect for textured styles.",
      brand: "Zira",
      rating: 4.8,
      reviews: 456,
      icon: "●",
      imageUrl: localImage("25_ZIRA_Hair_Clay.png"),
      ingredients: ["Clay", "Beeswax", "Coconut Oil"],

      benefits: ["Strong hold", "Matte finish", "Easy wash-out"],
      bestFor: ["Textured hair", "Short hair", "Daily styling"],
      skinType: ["All"],
      size: "100ml",
      discount: 10
    },
    {
      name: "Coconut Oil Hair Tonic",
      categoryId: byName("Hair Care"),
      price: 749,
      stock: 42,
      desc: "Strengthen and nourish hair. Reduces hair fall naturally.",
      brand: "Zira",
      rating: 4.5,
      reviews: 324,
      icon: "🥥",      imageUrl: localImage("28_ZIRA_Hair_Oil.png"),

      benefits: ["Reduces hair fall", "Strengthens roots", "Nourishes"],
      bestFor: ["Hair loss", "Weak hair", "Weekly massage"],
      skinType: ["All"],
      size: "200ml",
      discount: 15
    },
    {
      name: "Charcoal Shampoo",
      categoryId: byName("Hair Care"),
      price: 599,
      stock: 70,
      desc: "Deep cleansing shampoo for men. Removes toxins from scalp.",
      brand: "Zira",
      rating: 4.6,
      reviews: 378,
      icon: "🧼",      imageUrl: localImage("29_ZIRA_Anti_Dandruff_Shampoo.png"),

      benefits: ["Deep cleanse", "Scalp detox", "Shine"],
      bestFor: ["Oily scalp", "Daily use", "Pollution"],
      skinType: ["All"],
      size: "250ml",
      discount: 25
    },

    // Fragrances
    {
      name: "Zira No.7 Eau de Parfum",
      categoryId: byName("Fragrances"),
      price: 3499,
      stock: 18,
      desc: "Oudh, leather, black pepper. Long-lasting signature scent.",
      brand: "Zira Premium",
      rating: 4.9,
      reviews: 234,
      icon: "✦",
      imageUrl: localImage("40_ZIRA_Perfume.png"),
      ingredients: ["Oudh Oil", "Leather Accord", "Black Pepper"],

      benefits: ["Long-lasting", "Unique scent", "Premium quality"],
      bestFor: ["All occasions", "Evening wear", "Office"],
      skinType: ["All"],
      size: "100ml",
      discount: 5
    },
    {
      name: "Fresh Citrus Cologne",
      categoryId: byName("Fragrances"),
      price: 1999,
      stock: 25,
      desc: "Refreshing citrus and mint blend. Perfect for daily wear.",
      brand: "Zira",
      rating: 4.4,
      reviews: 156,
      icon: "🍋",
      imageUrl: localImage("41_ZIRA_Eau_de_Toilette.png"),
      ingredients: ["Lemon Oil", "Mint", "Bergamot"],

      benefits: ["Fresh scent", "Long-lasting", "Refreshing"],
      bestFor: ["Daily wear", "Office", "Summer"],
      skinType: ["All"],
      size: "100ml",
      discount: 10
    },
    {
      name: "Woody Attar - Premium",
      categoryId: byName("Fragrances"),
      price: 2499,
      stock: 15,
      desc: "Traditional woody attar. Exotic and mysterious fragrance.",
      brand: "Zira Premium",
      rating: 4.7,
      reviews: 189,
      icon: "🌲",
      imageUrl: localImage("42_ZIRA_Cologne.png"),
      ingredients: ["Sandalwood", "Cedar", "Agarwood"],

      benefits: ["Unique scent", "Long-lasting", "Exotic"],
      bestFor: ["Evening", "Special occasions", "Collectors"],
      skinType: ["All"],
      size: "12ml",
      discount: 0
    },

    // Body Care
    {
      name: "Men's Body Wash",
      categoryId: byName("Body Care"),
      price: 449,
      stock: 80,
      desc: "Energizing body wash. Charcoal and mint for fresh feel.",
      brand: "Zira",
      rating: 4.5,
      reviews: 267,
      icon: "💧",
      imageUrl: localImage("34_ZIRA_Body_Wash.png"),
      ingredients: ["Charcoal", "Mint", "Aloe Vera"],

      benefits: ["Deep cleanse", "Fresh scent", "Gentle"],
      bestFor: ["Daily use", "All body types", "Shower"],
      skinType: ["All"],
      size: "300ml",
      discount: 20
    },
    {
      name: "Deodorant - Charcoal Fresh",
      categoryId: byName("Body Care"),
      price: 349,
      stock: 95,
      desc: "24-hour protection. Sweat-resistant and antiperspirant.",
      brand: "Zira",
      rating: 4.6,
      reviews: 418,
      icon: "🚫",
      imageUrl: localImage("38_ZIRA_Deodorant_Spray.png"),
      ingredients: ["Charcoal", "Zinc", "Mineral Salts"],

      benefits: ["24-hour protection", "Sweat control", "Fresh scent"],
      bestFor: ["Daily use", "Sports", "Gym"],
      skinType: ["All"],
      size: "150ml",
      discount: 15
    },

    // Accessories
    {
      name: "Complete Grooming Kit - Starter",
      categoryId: byName("Accessories"),
      price: 2999,
      stock: 12,
      desc: "Face wash, moisturizer, beard oil & more. Everything to start.",
      brand: "Zira",
      rating: 4.8,
      reviews: 203,
      icon: "🎁",
      imageUrl: localImage("50_ZIRA_Grooming_Kit.png"),
      ingredients: ["Multiple"],

      benefits: ["Complete kit", "Value for money", "Travel-friendly"],
      bestFor: ["Beginners", "Gift", "Travel"],
      skinType: ["All"],
      size: "Kit",
      discount: 30
    },
    // More Face Care Products
    {
      name: "ZIRA Sunscreen SPF 50",
      categoryId: byName("Face Care"),
      price: 699,
      stock: 75,
      desc: "Broad spectrum protection. Water-resistant and lightweight formula.",
      brand: "ZIRA",
      rating: 4.7,
      reviews: 425,
      icon: "☀️",
      imageUrl: localImage("08_ZIRA_Sunscreen_SPF_50.png"),
      ingredients: ["Zinc Oxide", "Titanium Dioxide", "Aloe Vera"],
      benefits: ["UV protection", "Water-resistant", "Lightweight"],
      bestFor: ["Outdoor", "Beach", "Daily wear"],
      skinType: ["All"],
      size: "100ml",
      discount: 12
    },
    {
      name: "ZIRA Night Cream",
      categoryId: byName("Face Care"),
      price: 749,
      stock: 60,
      desc: "Rich night moisturizer. Repairs and rejuvenates skin overnight.",
      brand: "ZIRA",
      rating: 4.8,
      reviews: 356,
      icon: "🌙",
      imageUrl: localImage("09_ZIRA_Night_Cream.png"),
      ingredients: ["Retinol", "Hyaluronic Acid", "Vitamin E"],
      benefits: ["Deep nourishment", "Anti-aging", "Skin repair"],
      bestFor: ["Dry skin", "Aging skin", "Night care"],
      skinType: ["Dry", "Mature"],
      size: "50ml",
      discount: 10
    },
    {
      name: "ZIRA Under Eye Cream",
      categoryId: byName("Face Care"),
      price: 649,
      stock: 70,
      desc: "Targets dark circles and puffiness. Gentle caffeine complex.",
      brand: "ZIRA",
      rating: 4.6,
      reviews: 298,
      icon: "👁️",
      imageUrl: localImage("10_ZIRA_Under_Eye_Cream.png"),
      ingredients: ["Caffeine", "Arnica", "Vitamin K"],
      benefits: ["Reduces dark circles", "Anti-puffiness", "Brightening"],
      bestFor: ["Dark circles", "Tired eyes", "All ages"],
      skinType: ["All"],
      size: "20ml",
      discount: 15
    },
    {
      name: "ZIRA Lip Balm",
      categoryId: byName("Face Care"),
      price: 199,
      stock: 120,
      desc: "Moisturizing lip care. SPF protection with natural oils.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 512,
      icon: "👄",
      imageUrl: localImage("11_ZIRA_Lip_Balm.png"),
      ingredients: ["Beeswax", "Shea Butter", "Vitamin E"],
      benefits: ["Moisturizing", "SPF protection", "Long-lasting"],
      bestFor: ["Daily use", "Dry lips", "All seasons"],
      skinType: ["All"],
      size: "5g",
      discount: 20
    },
    
    // More Beard Care Products
    {
      name: "ZIRA Beard Shampoo",
      categoryId: byName("Beard Care"),
      price: 349,
      stock: 85,
      desc: "Gentle beard cleanser. Maintains softness and shine.",
      brand: "ZIRA",
      rating: 4.6,
      reviews: 267,
      icon: "🧼",
      imageUrl: localImage("15_ZIRA_Beard_Shampoo.png"),
      ingredients: ["Coconut Oil", "Argan Oil", "Tea Tree"],
      benefits: ["Gentle cleanse", "Shine", "Anti-itch"],
      bestFor: ["Beard care", "Daily use", "All beard types"],
      skinType: ["All"],
      size: "200ml",
      discount: 18
    },
    {
      name: "ZIRA Beard Conditioner",
      categoryId: byName("Beard Care"),
      price: 349,
      stock: 70,
      desc: "Deep conditioning treatment. Softens and smooths beard.",
      brand: "ZIRA",
      rating: 4.7,
      reviews: 245,
      icon: "💆",
      imageUrl: localImage("13_ZIRA_Beard_Balm.png"),
      ingredients: ["Coconut Milk", "Jojoba Oil", "Vitamin B5"],
      benefits: ["Softening", "Conditioning", "Shine"],
      bestFor: ["Coarse beards", "Long beards", "Weekly care"],
      skinType: ["All"],
      size: "200ml",
      discount: 15
    },
    {
      name: "ZIRA Beard Growth Serum",
      categoryId: byName("Beard Care"),
      price: 599,
      stock: 45,
      desc: "Promotes beard growth. Vitamin-enriched formula.",
      brand: "ZIRA",
      rating: 4.8,
      reviews: 389,
      icon: "📈",
      imageUrl: localImage("17_ZIRA_Beard_Growth_Serum.png"),
      ingredients: ["Biotin", "Neem", "Fenugreek"],
      benefits: ["Growth promotion", "Thickness", "Strength"],
      bestFor: ["Patchy beards", "Growth seeker", "Sparse beards"],
      skinType: ["All"],
      size: "30ml",
      discount: 12
    },
    {
      name: "ZIRA Shaving Cream",
      categoryId: byName("Beard Care"),
      price: 279,
      stock: 95,
      desc: "Rich lather shaving cream. Reduces razor burn.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 423,
      icon: "🧴",
      imageUrl: localImage("18_ZIRA_Shaving_Cream.png"),
      ingredients: ["Coconut Oil", "Glycerin", "Aloe Vera"],
      benefits: ["Smooth shave", "Razor protection", "Moisturizing"],
      bestFor: ["Daily shave", "Sensitive skin", "All razor types"],
      skinType: ["All"],
      size: "150ml",
      discount: 25
    },
    {
      name: "ZIRA Shaving Foam",
      categoryId: byName("Beard Care"),
      price: 249,
      stock: 100,
      desc: "Quick foaming shave. Easy application and rinse.",
      brand: "ZIRA",
      rating: 4.4,
      reviews: 356,
      icon: "☁️",
      imageUrl: localImage("19_ZIRA_Shaving_Foam.png"),
      ingredients: ["Coconut Foam", "Tea Tree", "Glycerin"],
      benefits: ["Quick foam", "Easy rinse", "Smooth shave"],
      bestFor: ["Quick shaves", "Busy mornings", "All skin types"],
      skinType: ["All"],
      size: "200ml",
      discount: 20
    },
    {
      name: "ZIRA After Shave Lotion",
      categoryId: byName("Beard Care"),
      price: 299,
      stock: 80,
      desc: "Cooling after-shave care. Prevents ingrown hairs.",
      brand: "ZIRA",
      rating: 4.6,
      reviews: 298,
      icon: "❄️",
      imageUrl: localImage("20_ZIRA_After_Shave_Lotion.png"),
      ingredients: ["Menthol", "Aloe Vera", "Witch Hazel"],
      benefits: ["Cooling effect", "Soothing", "Prevents ingrown"],
      bestFor: ["Post-shave", "Sensitive skin", "Daily use"],
      skinType: ["All"],
      size: "100ml",
      discount: 15
    },
    {
      name: "ZIRA After Shave Gel",
      categoryId: byName("Beard Care"),
      price: 329,
      stock: 75,
      desc: "Gel-based after-shave. Quick absorb formula.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 267,
      icon: "✨",
      imageUrl: localImage("21_ZIRA_After_Shave_Gel.png"),
      ingredients: ["Aloe Vera Gel", "Chamomile", "Vitamin E"],
      benefits: ["Quick absorb", "Non-sticky", "Soothing"],
      bestFor: ["Post-shave", "Sensitive skin", "Summer"],
      skinType: ["All"],
      size: "100ml",
      discount: 12
    },
    {
      name: "ZIRA Safety Razor",
      categoryId: byName("Beard Care"),
      price: 799,
      stock: 30,
      desc: "Professional safety razor. Stainless steel construction.",
      brand: "ZIRA",
      rating: 4.9,
      reviews: 456,
      icon: "🔪",
      imageUrl: localImage("22_ZIRA_Safety_Razor.png"),
      ingredients: ["Stainless Steel"],
      benefits: ["Precision shave", "Durable", "Eco-friendly"],
      bestFor: ["Wet shave", "Professional", "Sensitive skin"],
      skinType: ["All"],
      size: "1pc",
      discount: 8
    },
    {
      name: "ZIRA Shaving Brush",
      categoryId: byName("Beard Care"),
      price: 499,
      stock: 35,
      desc: "Premium shaving brush. Soft bristles for smooth lather.",
      brand: "ZIRA",
      rating: 4.7,
      reviews: 234,
      icon: "🖌️",
      imageUrl: localImage("23_ZIRA_Shaving_Brush.png"),
      ingredients: ["Badger Hair", "Wood Handle"],
      benefits: ["Smooth lather", "Exfoliation", "Premium feel"],
      bestFor: ["Wet shave", "Lather creation", "Collectors"],
      skinType: ["All"],
      size: "1pc",
      discount: 10
    },

    // More Hair Care Products
    {
      name: "ZIRA Hair Gel",
      categoryId: byName("Hair Care"),
      price: 279,
      stock: 90,
      desc: "Strong hold hair gel. Washable and non-sticky.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 345,
      icon: "💇",
      imageUrl: localImage("48_ZIRA_Hair_Comb.png"),
      ingredients: ["Polymer", "Aloe Vera", "Vitamin E"],
      benefits: ["Strong hold", "Non-sticky", "Washable"],
      bestFor: ["Styling", "Daily use", "All hair types"],
      skinType: ["All"],
      size: "150ml",
      discount: 18
    },
    {
      name: "ZIRA Hair Serum",
      categoryId: byName("Hair Care"),
      price: 349,
      stock: 65,
      desc: "Lightweight hair serum. Adds shine and smoothness.",
      brand: "ZIRA",
      rating: 4.6,
      reviews: 289,
      icon: "💧",
      imageUrl: localImage("27_ZIRA_Hair_Serum.png"),
      ingredients: ["Argan Oil", "Jojoba Oil", "Vitamin E"],
      benefits: ["Shine", "Smoothness", "Frizz control"],
      bestFor: ["Dry hair", "Frizzy hair", "Daily use"],
      skinType: ["All"],
      size: "30ml",
      discount: 20
    },
    {
      name: "ZIRA Hair Oil",
      categoryId: byName("Hair Care"),
      price: 299,
      stock: 85,
      desc: "Traditional hair oil. Deep conditioning treatment.",
      brand: "ZIRA",
      rating: 4.7,
      reviews: 412,
      icon: "🫒",
      imageUrl: localImage("28_ZIRA_Hair_Oil.png"),
      ingredients: ["Coconut Oil", "Sesame Oil", "Brahmi"],
      benefits: ["Deep conditioning", "Scalp health", "Growth"],
      bestFor: ["Weekly care", "Dry scalp", "Hair growth"],
      skinType: ["All"],
      size: "200ml",
      discount: 15
    },
    {
      name: "ZIRA Anti-Dandruff Shampoo",
      categoryId: byName("Hair Care"),
      price: 379,
      stock: 70,
      desc: "Targets dandruff and flaking. Zinc pyrithione formula.",
      brand: "ZIRA",
      rating: 4.6,
      reviews: 356,
      icon: "❌",
      imageUrl: localImage("29_ZIRA_Anti_Dandruff_Shampoo.png"),
      ingredients: ["Zinc Pyrithione", "Ketoconazole", "Tea Tree"],
      benefits: ["Anti-dandruff", "Scalp health", "Flake control"],
      bestFor: ["Dandruff", "Oily scalp", "Regular use"],
      skinType: ["All"],
      size: "200ml",
      discount: 12
    },
    {
      name: "ZIRA Hair Conditioner",
      categoryId: byName("Hair Care"),
      price: 299,
      stock: 75,
      desc: "Moisturizing conditioner. Softens and smooths hair.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 298,
      icon: "🧴",
      imageUrl: localImage("30_ZIRA_Hair_Conditioner.png"),
      ingredients: ["Coconut Milk", "Argan Oil", "Panthenol"],
      benefits: ["Moisturizing", "Softness", "Shine"],
      bestFor: ["Dry hair", "Daily use", "Post-shampoo"],
      skinType: ["All"],
      size: "200ml",
      discount: 18
    },
    {
      name: "ZIRA Hair Growth Serum",
      categoryId: byName("Hair Care"),
      price: 649,
      stock: 40,
      desc: "Promotes hair growth. Clinically tested formula.",
      brand: "ZIRA",
      rating: 4.8,
      reviews: 378,
      icon: "📈",
      imageUrl: localImage("31_ZIRA_Hair_Growth_Serum.png"),
      ingredients: ["Biotin", "Minoxidil", "Vitamin Complex"],
      benefits: ["Growth promotion", "Thickness", "Volume"],
      bestFor: ["Hair loss", "Thin hair", "Growth"],
      skinType: ["All"],
      size: "30ml",
      discount: 10
    },
    {
      name: "ZIRA Hair Styling Spray",
      categoryId: byName("Hair Care"),
      price: 249,
      stock: 95,
      desc: "Light holding spray. Easy to wash out.",
      brand: "ZIRA",
      rating: 4.4,
      reviews: 267,
      icon: "💨",
      imageUrl: localImage("32_ZIRA_Hair_Styling_Spray.png"),
      ingredients: ["Polymer Resin", "Alcohol", "Propellant"],
      benefits: ["Light hold", "Flexible", "Easy wash"],
      bestFor: ["Styling", "Finishing", "All hair types"],
      skinType: ["All"],
      size: "200ml",
      discount: 22
    },
    {
      name: "ZIRA Dry Shampoo",
      categoryId: byName("Hair Care"),
      price: 329,
      stock: 85,
      desc: "Quick clean between washes. Absorbs oil instantly.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 345,
      icon: "☁️",
      imageUrl: localImage("33_ZIRA_Dry_Shampoo.png"),
      ingredients: ["Talc-free Powder", "Fragrance"],
      benefits: ["Oil absorption", "Quick refresh", "Volume"],
      bestFor: ["Oily hair", "Quick fix", "Between washes"],
      skinType: ["All"],
      size: "150ml",
      discount: 20
    },

    // More Body Care Products
    {
      name: "ZIRA Soap Bar",
      categoryId: byName("Body Care"),
      price: 149,
      stock: 150,
      desc: "Natural soap bar. Mild and moisturizing formula.",
      brand: "ZIRA",
      rating: 4.4,
      reviews: 512,
      icon: "🧼",
      imageUrl: localImage("35_ZIRA_Soap_Bar.png"),
      ingredients: ["Coconut Oil", "Olive Oil", "Natural Extracts"],
      benefits: ["Gentle clean", "Moisturizing", "Natural"],
      bestFor: ["Daily use", "All skin", "Eco-friendly"],
      skinType: ["All"],
      size: "100g",
      discount: 25
    },
    {
      name: "ZIRA Body Lotion",
      categoryId: byName("Body Care"),
      price: 329,
      stock: 70,
      desc: "Light body lotion. Quick absorb and non-greasy.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 389,
      icon: "🧴",
      imageUrl: localImage("36_ZIRA_Body_Lotion.png"),
      ingredients: ["Shea Butter", "Glycerin", "Aloe Vera"],
      benefits: ["Moisturizing", "Soft skin", "Non-greasy"],
      bestFor: ["Daily use", "Dry skin", "All skin types"],
      skinType: ["All"],
      size: "200ml",
      discount: 15
    },
    {
      name: "ZIRA Body Mist",
      categoryId: byName("Body Care"),
      price: 279,
      stock: 85,
      desc: "Light fragrance mist. Perfect for layering.",
      brand: "ZIRA",
      rating: 4.4,
      reviews: 267,
      icon: "💨",
      imageUrl: localImage("37_ZIRA_Body_Mist.png"),
      ingredients: ["Fragrance", "Alcohol", "Water"],
      benefits: ["Fresh scent", "Light layer", "Refreshing"],
      bestFor: ["Daily wear", "Hot weather", "Layering"],
      skinType: ["All"],
      size: "100ml",
      discount: 18
    },
    {
      name: "ZIRA Deodorant Spray",
      categoryId: byName("Body Care"),
      price: 199,
      stock: 120,
      desc: "Quick dry deodorant spray. 12-hour protection.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 434,
      icon: "☁️",
      imageUrl: localImage("39_ZIRA_Roll_On_Deodorant.png"),
      ingredients: ["Aluminum Salts", "Zinc", "Fragrance"],
      benefits: ["Long protection", "Quick dry", "Fresh scent"],
      bestFor: ["Daily use", "Sports", "Active men"],
      skinType: ["All"],
      size: "150ml",
      discount: 20
    },
    {
      name: "ZIRA Roll-On Deodorant",
      categoryId: byName("Body Care"),
      price: 179,
      stock: 130,
      desc: "Roll-on deodorant. Precise application.",
      brand: "ZIRA",
      rating: 4.4,
      reviews: 398,
      icon: "🔄",
      imageUrl: localImage("39_ZIRA_Roll_On_Deodorant.png"),
      ingredients: ["Aluminum Chloride", "Aloe Vera", "Tea Tree"],
      benefits: ["Precision", "Long-lasting", "Gentle"],
      bestFor: ["Daily use", "Sensitive skin", "Travel"],
      skinType: ["All"],
      size: "50ml",
      discount: 18
    },
    {
      name: "ZIRA Foot Cream",
      categoryId: byName("Body Care"),
      price: 299,
      stock: 60,
      desc: "Intensive foot treatment. Softens cracked heels.",
      brand: "ZIRA",
      rating: 4.6,
      reviews: 234,
      icon: "🦶",
      imageUrl: localImage("43_ZIRA_Foot_Cream.png"),
      ingredients: ["Urea", "Glycerin", "Cocoa Butter"],
      benefits: ["Softening", "Crack healing", "Moisturizing"],
      bestFor: ["Dry feet", "Cracked heels", "Weekly care"],
      skinType: ["All"],
      size: "100ml",
      discount: 12
    },
    {
      name: "ZIRA Foot Spray",
      categoryId: byName("Body Care"),
      price: 249,
      stock: 70,
      desc: "Antifungal foot spray. Prevents odor.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 267,
      icon: "🌡️",
      imageUrl: localImage("44_ZIRA_Foot_Spray.png"),
      ingredients: ["Miconazole", "Menthol", "Talc"],
      benefits: ["Antifungal", "Odor control", "Cooling"],
      bestFor: ["Sweaty feet", "Odor prevention", "Athletes"],
      skinType: ["All"],
      size: "100ml",
      discount: 15
    },
    {
      name: "ZIRA Hand Cream",
      categoryId: byName("Body Care"),
      price: 249,
      stock: 90,
      desc: "Lightweight hand cream. Absorbs quickly.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 345,
      icon: "🤝",
      imageUrl: localImage("45_ZIRA_Hand_Cream.png"),
      ingredients: ["Glycerin", "Shea Butter", "Almond Oil"],
      benefits: ["Moisturizing", "Quick absorb", "Soft hands"],
      bestFor: ["Daily use", "Dry hands", "On-the-go"],
      skinType: ["All"],
      size: "75ml",
      discount: 20
    },

    // More Fragrance Products
    {
      name: "ZIRA Cologne Classic",
      categoryId: byName("Fragrances"),
      price: 699,
      stock: 50,
      desc: "Classic cologne scent. Versatile for all occasions.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 389,
      icon: "🧴",
      imageUrl: localImage("42_ZIRA_Cologne.png"),
      ingredients: ["Top Notes", "Heart Notes", "Base Notes"],
      benefits: ["Versatile", "Long-lasting", "Classic"],
      bestFor: ["Daily wear", "Office", "All occasions"],
      skinType: ["All"],
      size: "100ml",
      discount: 15
    },

    // More Accessories Products
    {
      name: "ZIRA Nail Care Kit",
      categoryId: byName("Accessories"),
      price: 499,
      stock: 40,
      desc: "Complete nail care set. 5 tools included.",
      brand: "ZIRA",
      rating: 4.6,
      reviews: 234,
      icon: "✌️",
      imageUrl: localImage("46_ZIRA_Nail_Care_Kit.png"),
      ingredients: ["Stainless Steel"],
      benefits: ["Complete kit", "Durable", "Travel-friendly"],
      bestFor: ["Nail care", "Grooming", "Travel"],
      skinType: ["All"],
      size: "Kit",
      discount: 12
    },
    {
      name: "ZIRA Beard Comb",
      categoryId: byName("Accessories"),
      price: 349,
      stock: 55,
      desc: "Wooden beard comb. Reduces static and breakage.",
      brand: "ZIRA",
      rating: 4.7,
      reviews: 267,
      icon: "🧔",
      imageUrl: localImage("47_ZIRA_Beard_Comb.png"),
      ingredients: ["Wood"],
      benefits: ["Anti-static", "Breakage prevention", "Premium feel"],
      bestFor: ["Beard grooming", "Daily use", "Long beards"],
      skinType: ["All"],
      size: "1pc",
      discount: 10
    },
    {
      name: "ZIRA Hair Comb",
      categoryId: byName("Accessories"),
      price: 249,
      stock: 75,
      desc: "Fine-tooth hair comb. For wet and dry use.",
      brand: "ZIRA",
      rating: 4.5,
      reviews: 298,
      icon: "💇",
      imageUrl: localImage("48_ZIRA_Hair_Comb.png"),
      ingredients: ["Plastic/Wood"],
      benefits: ["Anti-static", "Detangling", "Durable"],
      bestFor: ["Hair care", "Daily use", "All hair types"],
      skinType: ["All"],
      size: "1pc",
      discount: 15
    },
    {
      name: "ZIRA Electric Trimmer",
      categoryId: byName("Accessories"),
      price: 1499,
      stock: 18,
      desc: "Cordless electric trimmer. 60-minute runtime.",
      brand: "ZIRA Premium",
      rating: 4.8,
      reviews: 456,
      icon: "⚡",
      imageUrl: localImage("49_ZIRA_Electric_Trimmer.png"),
      ingredients: ["Stainless Steel Blades"],
      benefits: ["Cordless", "Long runtime", "Precision"],
      bestFor: ["Beard trim", "Hair cut", "Professional use"],
      skinType: ["All"],
      size: "1pc",
      discount: 8
    },
    {
      name: "ZIRA Premium Grooming Kit",
      categoryId: byName("Accessories"),
      price: 2499,
      stock: 8,
      desc: "Ultimate grooming collection. All you need.",
      brand: "ZIRA Premium",
      rating: 4.9,
      reviews: 189,
      icon: "💼",
      imageUrl: localImage("50_ZIRA_Grooming_Kit.png"),
      ingredients: ["Multiple Premium Items"],
      benefits: ["Complete collection", "Premium items", "Gift-ready"],
      bestFor: ["Complete grooming", "Gift", "Collectors"],
      skinType: ["All"],
      size: "Kit",
      discount: 15
    },
  ]);

  await Blog.insertMany([
    { title: "Complete Men's Grooming Guide", author: "Zira Editorial", content: "Modern men's grooming is about more than just looking good—it's about feeling confident. From daily skincare routines to beard maintenance, we break down everything you need to know to build your perfect grooming regimen. Start with the basics: a good face wash, moisturizer, and beard oil if you're sporting facial hair." },
    { title: "Beard Oil vs Beard Balm: Which One Should You Use?", author: "Zira Editorial", content: "Confused about beard products? Beard oils are lightweight, absorb quickly, and provide shine and softness. They're perfect for daily use. Beard balms, on the other hand, offer more hold and structure for styling. Many grooming enthusiasts use both—oil for maintenance and balm for styling. The choice depends on your beard type and desired look." },
    { title: "Layering Fragrances Like a Pro", author: "Zira Editorial", content: "Attars and EDPs layer differently—apply attar to pulse points first, then a light mist of EDP over clothing. This creates a complex scent profile that develops throughout the day. Start with a 1:2 ratio of attar to EDP, and adjust based on your preference. Remember, fragrance is personal—choose what makes you feel confident." },
  ]);

  console.log("Seed complete. Admin login -> username: admin / password: admin123");
  console.log("Customer login -> username: karthikeyan0 / password: customer123");
  await mongoose.connection.close();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
